import os

SECRET_KEY = os.getenv("SECRET_KEY", "mergeflow-dev-secret-change-in-production")
DATABASE_URL = os.getenv(
    "DATABASE_URL",
    "postgresql://mergeflow_user:PLACEHOLDER@dpg-d7478unpm1nc738qbggg-a/mergeflow"
)
GITHUB_CLIENT_ID = os.getenv("GITHUB_CLIENT_ID", "")
GITHUB_CLIENT_SECRET = os.getenv("GITHUB_CLIENT_SECRET", "")
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY", "")
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET", "")

class Config:
    SECRET_KEY = SECRET_KEY
    SQLALCHEMY_DATABASE_URI = DATABASE_URL
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    GITHUB_CLIENT_ID = GITHUB_CLIENT_ID
    GITHUB_CLIENT_SECRET = GITHUB_CLIENT_SECRET
    STRIPE_SECRET_KEY = STRIPE_SECRET_KEY
    STRIPE_WEBHOOK_SECRET = STRIPE_WEBHOOK_SECRET
